from datetime import datetime
import re

def bold_keywords(text):
    # Basic heuristic: bold capitalized phrases or key market words
    keywords = [
        "Jenkins", "GitLab", "GitHub", "CloudBees", "AI", "LLM", "migration",
        "modernization", "pipeline", "DevOps", "IDP", "platform", "agentic"
    ]
    for word in keywords:
        text = re.sub(rf'\b({word})\b', r'**\1**', text)
    return text

def extract_tldr(insights):
    # Grab first 2–3 insight bullets
    bullets = [line for line in insights.split("\n") if line.strip().startswith("- ")]
    return "\n".join(bullets[:3])

def generate_exec_summary(insights, curated_sources):
    """
    Executive-style summary:
    - TL;DR
    - Bolded keywords
    - Styled headers
    - Trend delta placeholder
    """
    date = datetime.utcnow().strftime("%Y-%m-%d")
    source_md = "\n".join(f"- [{title}]({url})" for title, url in curated_sources)

    insights_bolded = bold_keywords(insights)
    tldr = extract_tldr(insights_bolded)

    return f"""
# 🚨 **CloudBees Market Watch – Executive Brief** ({date})

---

## ⚡️ **TL;DR (Top Signals)**

{tldr}

---

## 🔥 **Key Market Signals**

⬇️ *Insights detected in the last 24 hours:*

{insights_bolded}

---

## 📈 **Trend Deltas**

_Coming soon: directional shifts based on weekly, monthly, and quarterly comparisons._

---

## 📚 **Source Deck for PMs & PMMs**

Verify insights or explore full articles:

{source_md}

---

✅ _Automatically generated by the Market Watch Agent by Shelly Eisen Livneh._
"""
